### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by InvokerMaster** [eliteluxury/Beej-Ecommerce#2]
Do you have UK account? How's my site? @eliteluxury

**Comment by eliteluxury** [comment]
yeah i have @InvokerMaster , why?

**Comment by InvokerMaster** [comment]
I know your account ;)

**Comment by eliteluxury** [comment]
OK, did you see it?

**Comment by InvokerMaster** [comment]
Yeah

**Comment by eliteluxury** [comment]
how is it? don't look it for many times, it's only one account of mine.

**Comment by InvokerMaster** [comment]
Can you give me 1 account?

**Comment by InvokerMaster** [comment]
Haha Okay

**Comment by eliteluxury** [comment]
don't you have any account?

**Comment by InvokerMaster** [comment]
Yes, I don't have any :(

**Comment by eliteluxury** [comment]
hmm, not good.

**Comment by eliteluxury** [comment]
but you have jobs now?

**Comment by InvokerMaster** [comment]
Yes.

**Comment by InvokerMaster** [comment]
How's my portfolio?

**Comment by InvokerMaster** [comment]
The 7 months old job

**Comment by eliteluxury** [comment]
where is your portfolio?

**Comment by InvokerMaster** [comment]
Hmmmm
invokerpo.herokuapp.com

**Comment by InvokerMaster** [comment]
I really want to see you

**Comment by eliteluxury** [comment]
we are too!

**Comment by eliteluxury** [comment]
what is the site?

**Comment by InvokerMaster** [comment]
![Untitled](https://user-images.githubusercontent.com/31196185/54478468-b8752c80-47cf-11e9-8d8d-abd275a6811b.png)

**Comment by eliteluxury** [comment]
how many jobs you have?

**Comment by InvokerMaster** [comment]
Don't use this for portfolio okay?

**Comment by InvokerMaster** [comment]
only 1 ;(

**Comment by eliteluxury** [comment]
what do you mean?

**Comment by InvokerMaster** [comment]
and yourself?

**Comment by InvokerMaster** [comment]
Ah, that is my portfolio that is used for bidding

**Comment by eliteluxury** [comment]
where is the portfolio?

**Comment by InvokerMaster** [comment]
Hmmmm.
That url is my portfolio,

**Comment by eliteluxury** [comment]
![image](https://user-images.githubusercontent.com/35144713/54478525-fe9bb180-480a-11e9-93a8-a7009b2769f7.png)

**Comment by InvokerMaster** [comment]
Yes
you can click on left top images

**Comment by eliteluxury** [comment]
ahh

**Comment by eliteluxury** [comment]
it's WONDERFUL!!!!!!! ~~~~ right?

**Comment by InvokerMaster** [comment]
Yes a little...

**Comment by InvokerMaster** [comment]
Impressed?

**Comment by eliteluxury** [comment]
actually :+1:

**Comment by eliteluxury** [comment]
the projects are you worked on?

**Comment by InvokerMaster** [comment]
Yes

**Comment by eliteluxury** [comment]
looks great

**Comment by InvokerMaster** [comment]
All are vue

**Comment by eliteluxury** [comment]
nice ~ hey you genius, where did you get jobs?

**Comment by InvokerMaster** [comment]
Hmm. Upwork
But all from fake ;(

**Comment by eliteluxury** [comment]
Great.

**Comment by InvokerMaster** [comment]
What?? I don't even have one account.
Great???

**Comment by eliteluxury** [comment]
so it's GREAT!!!!
you don't have any account but have many jobs!!!!!!!!!!!!!~~~~~@!!!!!!!!!!!!!!!!!
you understand , pig????~~~~!!!!!!

**Comment by InvokerMaster** [comment]
No not really. I only have one job now that is 8 months old ~ ;(

**Comment by InvokerMaster** [comment]
How's the history of UK account?

**Comment by InvokerMaster** [comment]
Hello~~~

**Comment by eliteluxury** [comment]
hmm

**Comment by InvokerMaster** [comment]
????

**Comment by eliteluxury** [comment]
it's about lasted 5 months

**Comment by InvokerMaster** [comment]
Oh I see

**Comment by InvokerMaster** [comment]
100K

**Comment by eliteluxury** [comment]
what is 100K?

**Comment by InvokerMaster** [comment]
earning History ;)

**Comment by eliteluxury** [comment]
no it's 30K currently

**Comment by InvokerMaster** [comment]
Oh that is great

**Comment by InvokerMaster** [comment]
How did Monkey think month?

**Comment by eliteluxury** [comment]
monkey? which monkey?

**Comment by eliteluxury** [comment]
you pig?

**Comment by InvokerMaster** [comment]
The monkey which is 71 kgs

**Comment by eliteluxury** [comment]
:dancer:

**Comment by InvokerMaster** [comment]
Nam Jin

**Comment by eliteluxury** [comment]
he is doing so well

**Comment by eliteluxury** [comment]
nearly 40K

**Comment by InvokerMaster** [comment]
how much???

**Comment by InvokerMaster** [comment]
Last month ???

**Comment by InvokerMaster** [comment]
🙉

**Comment by eliteluxury** [comment]
see you later

**Comment by InvokerMaster** [comment]
Remove this issue
